name: stim_gen
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - asn1crypto=0.24.0
  - backports=1.0
  - backports.functools_lru_cache=1.5
  - backports_abc=0.5
  - blas=1.0
  - blosc=1.16.3
  - bzip2=1.0.8
  - ca-certificates=2019.9.11
  - cairo=1.14.12
  - certifi=2019.9.11
  - cffi=1.12.3
  - chardet=3.0.4
  - cloudpickle=1.2.2
  - configobj=5.0.6
  - cryptography=2.7
  - cycler=0.10.0
  - cython=0.29.13
  - cytoolz=0.10.1
  - dask-core=1.2.2
  - dbus=1.13.6
  - decorator=4.4.0
  - enum34=1.1.6
  - et_xmlfile=1.0.1
  - expat=2.2.6
  - ffmpeg=4.2
  - fontconfig=2.13.0
  - freetype=2.9.1
  - fribidi=1.0.5
  - funcsigs=1.0.2
  - functools32=3.2.3.2
  - future=0.17.1
  - futures=3.3.0
  - gettext=0.19.8.1
  - gevent=1.4.0
  - glib=2.56.2
  - gmp=6.1.2
  - gnutls=3.6.5
  - graphite2=1.3.13
  - greenlet=0.4.15
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - harfbuzz=1.8.8
  - hdf5=1.10.4
  - icu=58.2
  - idna=2.8
  - intel-openmp=2019.4
  - ipaddress=1.0.22
  - jdcal=1.4.1
  - jpeg=9b
  - kiwisolver=1.1.0
  - lame=3.100
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libflac=1.3.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libglu=9.0.0
  - libiconv=1.15
  - libogg=1.3.2
  - libpng=1.6.37
  - libsndfile=1.0.28
  - libsodium=1.0.16
  - libstdcxx-ng=9.1.0
  - libtiff=4.0.10
  - libuuid=1.0.3
  - libvorbis=1.3.5
  - libxcb=1.13
  - libxml2=2.9.9
  - libxslt=1.1.33
  - lxml=4.4.1
  - lz4-c=1.8.1.2
  - lzo=2.10
  - matplotlib=2.2.3
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.14
  - mkl_random=1.1.0
  - mock=3.0.5
  - moviepy=0.2.3.5
  - msgpack-python=0.6.1
  - ncurses=6.1
  - nettle=3.4.1
  - networkx=2.2
  - numexpr=2.7.0
  - numpy=1.16.5
  - numpy-base=1.16.5
  - olefile=0.46
  - openh264=1.8.0
  - openpyxl=2.6.3
  - openssl=1.1.1d
  - pandas=0.24.2
  - pango=1.42.4
  - patsy=0.5.1
  - pcre=8.43
  - pillow=6.1.0
  - pip=19.2.3
  - pixman=0.38.0
  - psutil=5.6.3
  - pycparser=2.19
  - pyopengl=3.1.1a1
  - pyopenssl=19.0.0
  - pyosf=1.0.5
  - pyparsing=2.4.2
  - pyqt=5.9.2
  - pyserial=3.4
  - pysocks=1.7.1
  - pysoundfile=0.10.2
  - pytables=3.5.2
  - python=2.7.16
  - python-bidi=0.4.2
  - python-dateutil=2.8.0
  - pytz=2019.2
  - pywavelets=1.0.3
  - pyyaml=5.1.2
  - pyzmq=18.1.0
  - qt=5.9.7
  - readline=7.0
  - requests=2.22.0
  - scikit-image=0.14.2
  - scipy=1.2.1
  - seaborn=0.9.0
  - setuptools=41.2.0
  - singledispatch=3.4.0.3
  - sip=4.19.8
  - six=1.12.0
  - snappy=1.1.7
  - sqlite=3.29.0
  - statsmodels=0.10.1
  - subprocess32=3.5.4
  - tk=8.6.8
  - toolz=0.10.0
  - tornado=5.1.1
  - tqdm=4.36.1
  - urllib3=1.24.2
  - wheel=0.33.6
  - wxpython=4.0.4
  - x264=1!152.20180806
  - xlrd=1.2.0
  - xz=5.2.4
  - yaml=0.1.7
  - zeromq=4.3.1
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - arabic-reshaper==2.0.15
    - astunparse==1.6.2
    - configparser==4.0.2
    - esprima==4.0.1
    - freetype-py==2.1.0.post1
    - gitdb2==2.0.6
    - gitpython==2.1.14
    - glfw==1.8.3
    - imageio==2.4.1
    - json-tricks==3.13.2
    - msgpack-numpy==0.4.4.3
    - pathlib==1.0.1
    - psychopy==3.2.3
    - psychopy-ext==0.6.0.4
    - pygame==1.9.6
    - pyglet==1.3.2
    - pyparallel==0.2.2
    - pysoundcard==0.5.2
    - python-gitlab==1.11.0
    - smmap2==2.0.5
    - sounddevice==0.3.14
    - zmq==0.0.0

